# Generated by Django 3.1.7 on 2021-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_info', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('subscribers', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'channel_link',
            },
        ),
    ]
